// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-8VumzcQDTe0gMlOjz1D_ME_dUm2pNUY',
    appId: '1:135165957591:web:9559e6c066d108e8e92792',
    messagingSenderId: '135165957591',
    projectId: 'converse-chatting',
    authDomain: 'converse-chatting.firebaseapp.com',
    storageBucket: 'converse-chatting.appspot.com',
    measurementId: 'G-M9HNN45ETY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_PBetiL5upcEpvdYzut9D8lgGpLnxSI',
    appId: '1:135165957591:android:0a95a3642406efbfe92792',
    messagingSenderId: '135165957591',
    projectId: 'converse-chatting',
    storageBucket: 'converse-chatting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAakRlN6c57SzakiUtJCDb5ADJdTQRX0rA',
    appId: '1:135165957591:ios:0d0c3f611bebae73e92792',
    messagingSenderId: '135165957591',
    projectId: 'converse-chatting',
    storageBucket: 'converse-chatting.appspot.com',
    iosBundleId: 'com.example.converse',
  );
}
